// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz5hdjdpi3aZB7hHwJ1v9b-WS5COagcOo',
    appId: '1:518157188019:web:3540769225e3db8ef069c6',
    messagingSenderId: '518157188019',
    projectId: 'abzurt-news',
    authDomain: 'abzurt-news.firebaseapp.com',
    storageBucket: 'abzurt-news.firebasestorage.app',
    measurementId: 'G-L53MEXNBJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggmYzj2s1XdaUybJTMB8dr3bY1Fl1ZKk',
    appId: '1:518157188019:android:3c64c309440e43aef069c6',
    messagingSenderId: '518157188019',
    projectId: 'abzurt-news',
    storageBucket: 'abzurt-news.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1h2XUgrltDGaOkihkKyVXyGXHLmvVZ1o',
    appId: '1:518157188019:ios:91d53907a05797d4f069c6',
    messagingSenderId: '518157188019',
    projectId: 'abzurt-news',
    storageBucket: 'abzurt-news.firebasestorage.app',
    iosBundleId: 'com.abzurt.abzurt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1h2XUgrltDGaOkihkKyVXyGXHLmvVZ1o',
    appId: '1:518157188019:ios:91d53907a05797d4f069c6',
    messagingSenderId: '518157188019',
    projectId: 'abzurt-news',
    storageBucket: 'abzurt-news.firebasestorage.app',
    iosBundleId: 'com.abzurt.abzurt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz5hdjdpi3aZB7hHwJ1v9b-WS5COagcOo',
    appId: '1:518157188019:web:18e7901ee693daedf069c6',
    messagingSenderId: '518157188019',
    projectId: 'abzurt-news',
    authDomain: 'abzurt-news.firebaseapp.com',
    storageBucket: 'abzurt-news.firebasestorage.app',
    measurementId: 'G-PVNSSEVJMZ',
  );
}
